-- ---------------------------------------------------------------------------
-- 002 — Reconcile the two identity systems (READ-ONLY diagnosis first)
--
-- This app has two tables that both describe "an admin":
--
--   users.role   -- 'member' | 'admin' | 'superadmin'
--   admins       -- a separate table with its own username/password/role
--
-- Everything that actually enforces authorization — requireAdmin(),
-- requireSuperadmin(), middleware.ts, /api/admin/status — reads `users.role`.
-- The `admins` table is only a directory that the Admin Management panel edits.
--
-- If your production admin exists ONLY in `admins`, they will be able to submit
-- the login form but will not pass authorization. /api/admin/login detects this
-- exact case and returns a 409 pointing at this file.
-- ---------------------------------------------------------------------------


-- STEP 1 — Diagnose. Read-only; safe to run any time.

-- 1a. Who currently has admin access (this is the list that matters):
SELECT id, username, email, role, created_at
FROM   users
WHERE  role IN ('admin', 'superadmin')
ORDER  BY role, id;

-- 1b. Who is in the legacy directory:
SELECT id, username, email, role, status, last_login
FROM   admins
ORDER  BY role, id;

-- 1c. Legacy admins with NO matching user account — these are the ones who
--     cannot sign in. If this returns rows, go to STEP 2.
SELECT a.id AS admin_id, a.username, a.email, a.role
FROM   admins a
LEFT   JOIN users u
       ON u.username = a.username OR u.email = a.email
WHERE  u.id IS NULL;

-- 1d. Legacy admins WITH a matching user whose role has not been promoted —
--     these just need STEP 3.
SELECT a.username, a.role AS admin_role, u.id AS user_id, u.role AS user_role
FROM   admins a
JOIN   users u
       ON u.username = a.username OR u.email = a.email
WHERE  u.role NOT IN ('admin', 'superadmin');


-- ---------------------------------------------------------------------------
-- STEP 2 — For legacy admins with no user account (from 1c).
--
-- Do NOT insert a user row with the password hash copied from `admins`. Create
-- the account through the normal sign-up flow so the hash is generated by the
-- current code path, then promote it with STEP 3. Copying hashes between tables
-- is how you end up with an account nobody can reset.
-- ---------------------------------------------------------------------------


-- STEP 3 — Promote a specific user to admin. Change the username, run it, and
-- verify. One user at a time; never a bulk UPDATE without a WHERE clause.

-- UPDATE users SET role = 'superadmin' WHERE username = 'REPLACE_ME' LIMIT 1;
-- UPDATE users SET role = 'admin'      WHERE username = 'REPLACE_ME' LIMIT 1;

-- Verify immediately afterwards:
-- SELECT id, username, role FROM users WHERE username = 'REPLACE_ME';


-- ---------------------------------------------------------------------------
-- STEP 4 — Confirm at least one superadmin exists before you log out.
-- If this returns 0, you are about to lock yourself out of the admin panel.
-- ---------------------------------------------------------------------------

SELECT COUNT(*) AS superadmin_count
FROM   users
WHERE  role = 'superadmin';
